# Generated by Django 3.2.8 on 2023-08-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_users_contact_friends_+', to='users.Contact'),
        ),
    ]
