# Generated by Django 3.2.8 on 2023-09-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rights',
            name='unhideComment',
            field=models.BooleanField(default=False),
        ),
    ]
