# Generated by Django 3.2.8 on 2023-09-25 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_rights_unhidecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='administration.permissiongroup'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to=settings.AUTH_USER_MODEL),
        ),
    ]
