# Generated by Django 2.0.7 on 2021-10-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogpost_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_email',
            field=models.EmailField(blank=True, default='ronnythenazi@gmail.com', max_length=254),
        ),
    ]
