# Generated by Django 3.2.8 on 2023-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pagevisitor_sitevisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisitor',
            name='session_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='session_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
