# Generated by Django 3.2.8 on 2023-08-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230810_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ChatNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to='chat.chat')),
            ],
        ),
    ]
