# Generated by Django 3.2.8 on 2023-08-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20230813_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmsgnotification',
            name='chat',
        ),
        migrations.AddField(
            model_name='chatmsgnotification',
            name='chat',
            field=models.ManyToManyField(related_name='chat_notifications', to='chat.Chat'),
        ),
    ]
