# Generated by Django 3.2.8 on 2023-08-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20230813_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
