# Generated by Django 2.0.7 on 2021-09-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210928_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('userstatus', models.CharField(choices=[('active', 'פעיל'), ('banned', 'הושבת'), ('deleted', 'נמחק'), ('deactivate', 'לא פעיל')], default='active', max_length=4)),
                ('usrrole', models.CharField(choices=[('regular', ''), ('moderator', 'מודרטור'), ('admin', 'מנהל'), ('owner', 'מאסטר')], default='regular', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='usrname',
        ),
        migrations.AddField(
            model_name='posts',
            name='author_email',
            field=models.EmailField(default='ronnythenazi@gmail.com', max_length=254, unique=True),
        ),
    ]
