# Generated by Django 3.2.8 on 2021-12-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogpost_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='regUsers',
        ),
    ]
