"""
Django settings for judonazim project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
# upload large files usuefyl link https://justdjango.com/blog/how-to-upload-large-files


import os
#import boto3
from django.core.management.utils import get_random_secret_key
from pathlib import Path
import sys
import dj_database_url
from dotenv import load_dotenv




#from . import cdn
#from .cdn import *

dotenv_path = os.path.join(os.path.dirname(__file__), '.env')
load_dotenv(dotenv_path)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") #or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get("DEBUG")) == "1"


AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',

]

INSTALLED_APPS = [
        'daphne',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        #personal
        'blog',
        #thirdparty
        'storages',
        'boto3',
        'ckeditor',
        #'magazine',
        'magazine.apps.MagazineConfig',
        'users',
        'social',
        'general',

        #'filer',
        #'ckeditor_filebrowser_filer',
        #'easy_thumbnails',
        'ckeditor_uploader',
        'analytics',
        'chat',
        'channels',


        'django.contrib.sites',
        'allauth',
        'allauth.account',
        'allauth.socialaccount',
        'allauth.socialaccount.providers.google',
        'allauth.socialaccount.providers.facebook',
        'allauth.socialaccount.providers.discord',
        'allauth.socialaccount.providers.spotify',
        'workers',
        'defender',
        'staticpages',

    ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'magazine.request_exposer.RequestExposerMiddleware',
    'defender.middleware.FailedLoginMiddleware',
]



ROOT_URLCONF = 'judonazim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates"),

        ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]
SOCIALACCOUNT_LOGIN_ON_GET=True

#LOGIN_REDIRECT_URL =    'magazine:magazineNews'


# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'SCOPE':{
            'profile',
            'email',
        },

        'AUTH_PARAMS':{'access_type':'online'},

        'APP': {
            'client_id': os.environ.get("GOOGLE_CLIENT_ID"),
            'secret': os.environ.get("GOOGLE_SECRET"),
            'key': '',
        }
    },



    'facebook': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:

        'APP': {
            'client_id': os.environ.get("FACEBOOK_CLIENT_ID"),
            'secret':os.environ.get("FACEBOOK_SECRET"),
            'key': '',
        }
    },


    'discord': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'SCOPE':{
            'identify',
            'email',
        },

        'AUTH_PARAMS':{'access_type':'online'},

        'APP': {
            'client_id': os.environ.get("DISCORD_CLIENT_ID"),
            'secret': os.environ.get("DISCORD_SECRET"),
            'key': '',
        }
    },

    'spotify': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:

        'APP': {
            'client_id': os.environ.get("SPOTIFY_CLIENT_ID"),
            'secret':os.environ.get("SPOTIFY_SECRET"),
            'key': '',
        }
    },

}



WSGI_APPLICATION = 'judonazim.wsgi.application'
ASGI_APPLICATION = 'judonazim.asgi.application'







DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
   }
}




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'users.validators.CustomPasswordValidator',
    },
]


DEFAULT_AUTO_FIELD='django.db.models.AutoField'



POSTGRES_DB = os.environ.get("POSTGRES_DB")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT")

POSTGRES_READY = (
    POSTGRES_DB is not None
    and POSTGRES_PASSWORD is not None
    and POSTGRES_USER is not None
    and POSTGRES_HOST is not None
    and POSTGRES_PORT is not None
)

if POSTGRES_READY:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,

        }
    }














REDIS_URL = str(os.environ.get("REDIS_CONNECTION_STRING"))


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_URL)],

               },

    }
}



if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')













LANGUAGE_CODE = 'en-us'
USE_I18N = True

USE_L10N = True

USE_TZ = False
#USE_TZ = True
TIME_ZONE = 'Israel'





from .cdn.conf import * # noqa

if DEBUG:
    """
    MEDIA_URL = '/'
    MEDIA_ROOT = os.path.join(BASE_DIR, '')
    """


    #MEDIA_URL = '{}/{}/'.format(AWS_S3_ENDPOINT_URL, 'media')
    MEDIA_URL = AWS_S3_ENDPOINT_URL +'/'
    MEDIA_ROOT = 'media/'
    #MEDIA_ROOT = 'media/'




else:

    MEDIA_URL = AWS_S3_ENDPOINT_URL +'/'
    MEDIA_ROOT = 'media/'


STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'blog', 'static'),
        os.path.join(BASE_DIR, 'magazine', 'static'),
        os.path.join(BASE_DIR, 'users', 'static'),
        os.path.join(BASE_DIR, 'social', 'static'),
        os.path.join(BASE_DIR, 'general', 'static'),
        os.path.join(BASE_DIR, 'analytics', 'static'),
        os.path.join(BASE_DIR, 'chat', 'static'),
        os.path.join(BASE_DIR, 'staticpages', 'static'),
      )
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')





#https://ronnythenazi.fra1.digitaloceanspaces.com
"""
CKEDITOR_CONFIGS = {
   'default': {
       'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['NumberedList','BulletedList'],
            ['Indent','Outdent'],
            ['Maximize'],
        ],
        'extraPlugins': 'justify,liststyle,indent',
   },
}
"""

"""
# your_app/settings.py
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'width': '100%'
    },
}
"""

CKEDITOR_IMAGE_BACKEND = "pillow"

#CKEDITOR_UPLOAD_PATH = 'ckeditor/uploads/'  commented at # added in 21-08-2023 21:33

#changed in 21-08-2023 21:33
CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_UPLOAD_SLUGIFY_FILENAME = True

#added in 25-08-2023 11:16
CKEDITOR_RESTRICT_BY_DATE = False

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar__Custom': [
     ['Styles', 'Format', 'Font', 'FontSize', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
     ['Link', 'Unlink', 'Anchor', 'Uploadimage'],
     ['Image','Update', 'Flash', 'Table', 'HorizontalRule'],
     ['TextColor', 'BGColor'],
     ['Smiley', 'SpecialChar'], ['Source'],
     ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
     ['NumberedList','BulletedList'],
     ['Indent','Outdent'],
     ['Maximize'],
     ['Preview'],
     ['Image'],
     #['FilerImage'],
 ],
        'width': '100%',
        'extraAllowedContent': 'iframe[*]',
        #'extraPlugins': 'filerimage',
        #'removePlugins': 'image',
        #"filebrowserUploadUrl":"upload/",


    },

}



ALLOWED_HOSTS = []

SITE_ID = 1

if not DEBUG:
    #ALLOWED_HOSTS = [os.environ.get("DJANGO_ALLOWED_HOSTS")]
    ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split()


#uncomment in 25/08/2023
#LOGIN_REDIRECT_URL = 'magazine:magazineNews'

LOGOUT_REDIRECT_URL = 'magazine:magazineNews'




SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')
#EMAIL_BACKEND = django.core.mail.backends.smtp.EmailBackend

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')

#FROM_EMAIL = 'ronnywasright.com' # replace with your address

if DEBUG:
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False
    #SENDGRID_SANDBOX_MODE_IN_DEBUG = True
    #SENDGRID_ECHO_TO_STDOUT=True
else:
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False


FORCE_SESSION_TO_ONE = False
FORCE_INACTIVE_USER_ENDSESSION = False






'''
from django.core.cache import caches, cache
KEY_PREFIX = cache.make_key('judonazim')




CACHES = {
    "default": {
        "BACKEND": "redis_cache.RedisCache",
        "LOCATION":"redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": KEY_PREFIX,
    }
}



CACHES = {
    "default": {
        "BACKEND": "redis_cache.RedisCache",
        "LOCATION":"redis://104.131.121.169:25061/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": KEY_PREFIX,
    }
}
'''
#SESSION_COOKIE_SECURE = False
#import urllib.parse
DROPLET_IP = os.environ.get('DROPLET_IP')
#DEFENDER_REDIS_PASSWORD_QUOTE = True
REDIS_SERVER_PASSWORD = os.environ.get('REDIS_SERVER_PASSWORD')
#REDIS_SERVER_PASSWORD = urllib.parse.quote(REDIS_SERVER_PASSWORD)
DEFENDER_REDIS_URL = REDIS_URL
#DEFENDER_REDIS_URL = "redis://104.131.121.169:6379/1"
DEFENDER_LOCKOUT_TEMPLATE = 'staticpages/too_many_login_attempts.html'
DEFENDER_USERNAME_FORM_FIELD = 'email'
