# Generated by Django 3.2.8 on 2023-09-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_contact_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='chats', to='users.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMsgNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to='chats.chat')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_notification', to='chats.message')),
                ('read_by_contacts', models.ManyToManyField(related_name='read_by_contacts', to='users.Contact')),
            ],
        ),
    ]
