# Generated by Django 3.2.8 on 2023-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatType',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
