# Generated by Django 3.2.8 on 2021-12-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publishstatus',
            field=models.CharField(choices=[('public', 'ציבורי'), ('private', 'פרטי')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(upload_to='media/posts/images/%d/%m/%Y/'),
        ),
    ]
