# Generated by Django 3.2.8 on 2021-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_remove_blogpost_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='posts/images/%Y/%m/%d/'),
        ),
    ]
