# Generated by Django 3.2.8 on 2021-12-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0021_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
