# Generated by Django 3.2.8 on 2021-12-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0023_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
