# Generated by Django 3.2.8 on 2021-12-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0039_alter_blogpost_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
