# Generated by Django 3.2.8 on 2022-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0053_comment_comment_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='members/profile/avatar'),
        ),
    ]
