# Generated by Django 3.2.8 on 2022-01-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0054_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to='members/profile/avatar'),
        ),
    ]
