# Generated by Django 3.2.8 on 2022-01-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0056_comment_of_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='datelastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='datepublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
