# Generated by Django 3.2.8 on 2022-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0088_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default='01/20/2022 14:48:58.125511'),
        ),
    ]
