# Generated by Django 3.2.8 on 2022-01-23 18:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0096_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='comment_of_comment',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
