# Generated by Django 3.2.8 on 2022-01-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0097_auto_20220123_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_of_comment',
            name='to_sub_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.comment_of_comment'),
        ),
    ]
