# Generated by Django 3.2.8 on 2022-01-24 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0099_alter_notification_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_usr',
            field=models.ForeignKey(blank=True, default=magazine.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment_of_comment',
            name='comment_of_comment_usr',
            field=models.ForeignKey(blank=True, default=magazine.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
