# Generated by Django 3.2.8 on 2022-01-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0102_auto_20220125_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_of_comment',
            name='to_sub_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_to', to='magazine.comment_of_comment'),
        ),
    ]
