# Generated by Django 3.2.8 on 2022-01-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0103_alter_comment_of_comment_to_sub_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comment_of_comment',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
