# Generated by Django 2.0.7 on 2021-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('subtitle', models.TextField(max_length=100)),
                ('usrname', models.TextField(default='ronnythenazi', max_length=50, unique=True)),
                ('datepublished', models.DateField(auto_now_add=True)),
                ('datelastupdated', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('publishstatus', models.CharField(choices=[('public', 'ציבורי'), ('private', 'פרטי')], default='private', max_length=2)),
                ('topic', models.TextField()),
            ],
        ),
    ]
