# Generated by Django 2.0.7 on 2021-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210928_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
