# Generated by Django 2.0.7 on 2021-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210930_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_email',
            field=models.EmailField(blank=True, default='ronnythenazi@gmail.com', max_length=254, unique=True),
        ),
    ]
