# Generated by Django 2.0.7 on 2021-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211001_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
