# Generated by Django 2.0.7 on 2021-10-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpost_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publishstatus',
            field=models.CharField(choices=[('public', 'ציבורי'), ('private', 'פרטי')], default='private', max_length=10),
        ),
    ]
