# Generated by Django 3.2.8 on 2021-10-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211008_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userstatus',
            field=models.CharField(choices=[('active', 'פעיל'), ('banned', 'הושבת'), ('deleted', 'נמחק'), ('deactivate', 'לא פעיל')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrrole',
            field=models.CharField(choices=[('regular', ''), ('moderator', 'מודרטור'), ('admin', 'מנהל'), ('owner', 'מאסטר')], default='regular', max_length=10),
        ),
    ]
