# Generated by Django 3.2.8 on 2021-12-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_blogpost_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regUsers',
            new_name='regUser',
        ),
    ]
