# Generated by Django 3.2.8 on 2021-12-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
