# Generated by Django 3.2.8 on 2021-12-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Moderators',
        ),
        migrations.DeleteModel(
            name='regUser',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
