# Generated by Django 3.2.8 on 2021-12-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20211213_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
