# Generated by Django 3.2.8 on 2021-12-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_auto_20211214_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publishstatus',
            field=models.CharField(choices=[('public', 'ציבורי'), ('private', 'פרטי')], default='public', max_length=10),
        ),
    ]
