# Generated by Django 3.2.8 on 2021-12-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumb',
        ),
    ]
