# Generated by Django 3.2.8 on 2021-12-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0031_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_email',
        ),
    ]
