# Generated by Django 3.2.8 on 2021-12-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0051_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
