# Generated by Django 3.2.8 on 2022-01-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0061_auto_20220112_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='members/profile/avatar'),
        ),
    ]
