# Generated by Django 3.2.8 on 2022-01-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0062_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='com_of_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='magazine.comment_of_comment'),
        ),
    ]
