# Generated by Django 3.2.8 on 2022-01-14 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0063_notification_com_of_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_of_comment',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_com_of_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment_of_comment',
            name='likes',
            field=models.ManyToManyField(related_name='likes_com_of_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
