# Generated by Django 3.2.8 on 2022-01-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0066_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='myfile',
        ),
    ]
