# Generated by Django 3.2.8 on 2022-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0067_rename_image_album_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='album/%Y/%m/%d'),
        ),
    ]
