# Generated by Django 3.2.8 on 2022-01-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0068_alter_album_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='myfile',
        ),
    ]
