# Generated by Django 3.2.8 on 2022-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0070_album_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='myfile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
