# Generated by Django 3.2.8 on 2022-01-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0071_alter_album_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='myfile',
            field=models.FileField(default='default.jpg', upload_to='album/%Y/%m/%d'),
        ),
    ]
