# Generated by Django 3.2.8 on 2022-01-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0076_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
