# Generated by Django 3.2.8 on 2022-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0091_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default='2022-01-20 16:01:32.518113'),
        ),
    ]
