# Generated by Django 3.2.8 on 2022-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0093_alter_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comment_of_comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default='תגובה למאמר', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='comment_of_comment',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
