# Generated by Django 3.2.8 on 2022-01-24 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0098_comment_of_comment_to_sub_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(default=magazine.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
