# Generated by Django 3.2.8 on 2023-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0105_auto_20220213_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('articles', models.ManyToManyField(related_name='articles', to='magazine.BlogPost')),
            ],
        ),
    ]
