# Generated by Django 3.2.8 on 2023-06-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0106_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='articles',
            field=models.ManyToManyField(null=True, related_name='articles', to='magazine.BlogPost'),
        ),
    ]
