# Generated by Django 3.2.8 on 2023-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0107_alter_labels_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles', to='magazine.BlogPost'),
        ),
    ]
