# Generated by Django 3.2.8 on 2023-06-30 16:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0108_alter_labels_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='comment_of_comment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
    ]
