# Generated by Django 3.2.8 on 2023-07-08 13:32

from django.db import migrations, models
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0110_profile_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[magazine.models.validate_min_length_2]),
        ),
    ]
