# Generated by Django 3.2.8 on 2023-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0112_auto_20230709_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='familial_status',
            field=models.CharField(blank=True, choices=[('single', 'רווק'), ('married', 'נשוי'), ('divorced', 'גרוש'), ('married_again', 'נשוי שוב')], max_length=100, null=True),
        ),
    ]
