# Generated by Django 3.2.8 on 2023-07-13 16:18

from django.db import migrations, models
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0114_alter_album_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mtdna',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='y_dna',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
