# Generated by Django 3.2.8 on 2023-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0115_auto_20230713_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
