# Generated by Django 3.2.8 on 2023-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0116_alter_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
