# Generated by Django 3.2.8 on 2023-09-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('magazine', '0119_auto_20230806_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='comment_of_comment',
            name='hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='administration.permissiongroup'),
        ),
    ]
